### ISSUE TITLE
请问一下这个是什么错误，我该如何进行？

### ISSUE THREAD

**Issue by rw1995** [dlyldxwl/fssd.pytorch#3]
(pytorch0.4.0) rw@rw:~/fssd.pytorch-master$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    from data import VOCroot,COCOroot
  File "/home/rw/fssd.pytorch-master/data/__init__.py", line 3, in <module>
    from .coco import COCODetection
  File "/home/rw/fssd.pytorch-master/data/coco.py", line 21, in <module>
    from utils.pycocotools.coco import COCO
  File "/home/rw/fssd.pytorch-master/utils/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/rw/fssd.pytorch-master/utils/pycocotools/mask.py", line 4, in <module>
    from . import _mask
ImportError: /home/rw/fssd.pytorch-master/utils/pycocotools/_mask.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

**Comment by rw1995** [comment]
我的配置是cuda9.0+cudnn7 pythorch0.4请问是什么问题导致的

**Comment by SWX1995swx** [comment]
我也遇到同样的问题，请问您解决了么？

**Comment by dlyldxwl** [comment]
Do you run this command?
./make.sh

**Comment by MaggieChenchen** [comment]
我也是同样的错误，OSError:_mask.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
不知是怎么解决呢？不好意思为比较小白  ./make.sh是什么意思呢？

**Comment by MaggieChenchen** [comment]
/home/maggie/anaconda3/bin/python3.6 /home/maggie/PycharmProjects/fssd.pytorch-master/demo.py
Traceback (most recent call last):
  File "/home/maggie/PycharmProjects/fssd.pytorch-master/demo.py", line 13, in <module>
    from data import VOCroot,COCOroot
  File "/home/maggie/PycharmProjects/fssd.pytorch-master/data/__init__.py", line 3, in <module>
    from .coco import COCODetection
  File "/home/maggie/PycharmProjects/fssd.pytorch-master/data/coco.py", line 21, in <module>
    from utils.pycocotools.coco import COCO
  File "/home/maggie/PycharmProjects/fssd.pytorch-master/utils/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/maggie/PycharmProjects/fssd.pytorch-master/utils/pycocotools/mask.py", line 7, in <module>
    _mask = cdll.LoadLibrary("/home/maggie/PycharmProjects/fssd.pytorch-master/utils/pycocotools/mmask.so")
  File "/home/maggie/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/maggie/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/maggie/PycharmProjects/fssd.pytorch-master/utils/pycocotools/mmask.so: undefined symbol: PyFPE_jbuf
跪求大佬看一下，我查了好久还是不懂怎么改，我也运行了make.sh文件但是我电脑没用cuda，我就把cuda的部分代码注释掉了，然后运行demo.py就出现了这个问题

**Comment by dlyldxwl** [comment]
I'll check my code on the afternoon~发自我的华为手机-------- 原始邮件 --------主题：Re: [dlyldxwl/fssd.pytorch] 请问一下这个是什么错误，我该如何进行？ (#3)发件人：MaggieChenchen 收件人："dlyldxwl/fssd.pytorch" 抄送：Chen yh <844518133@qq.com>,Comment /home/maggie/anaconda3/bin/python3.6 /home/maggie/PycharmProjects/fssd.pytorch-master/demo.py

Traceback (most recent call last):

File "/home/maggie/PycharmProjects/fssd.pytorch-master/demo.py", line 13, in 

from data import VOCroot,COCOroot

File "/home/maggie/PycharmProjects/fssd.pytorch-master/data/init.py", line 3, in 

from .coco import COCODetection

File "/home/maggie/PycharmProjects/fssd.pytorch-master/data/coco.py", line 21, in 

from utils.pycocotools.coco import COCO

File "/home/maggie/PycharmProjects/fssd.pytorch-master/utils/pycocotools/coco.py", line 55, in 

from . import mask as maskUtils

File "/home/maggie/PycharmProjects/fssd.pytorch-master/utils/pycocotools/mask.py", line 7, in 

_mask = cdll.LoadLibrary("/home/maggie/PycharmProjects/fssd.pytorch-master/utils/pycocotools/mmask.so")

File "/home/maggie/anaconda3/lib/python3.6/ctypes/init.py", line 426, in LoadLibrary

return self._dlltype(name)

File "/home/maggie/anaconda3/lib/python3.6/ctypes/init.py", line 348, in init

self._handle = _dlopen(self._name, mode)

OSError: /home/maggie/PycharmProjects/fssd.pytorch-master/utils/pycocotools/mmask.so: undefined symbol: PyFPE_jbuf

跪求大佬看一下，我查了好久还是不懂怎么改，我也运行了make.sh文件但是我电脑没用cuda，我就把cuda的部分代码注释掉了，然后运行demo.py就出现了这个问题



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/dlyldxwl/fssd.pytorch/issues/3#issuecomment-490335338",

"url": "https://github.com/dlyldxwl/fssd.pytorch/issues/3#issuecomment-490335338",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by dlyldxwl** [comment]
@MaggieChenchen 
Please delete the command `from data import VOCroot,COCOroot` in demo.py, and then run this code.
Furthermore, if you don't use cuda, you only need turn the cuda switch to False in the code.

**Comment by rw1995** [comment]
> Do you run this command?
> ./make.sh

sorry，他依然是错误的，，，，，，，，
`(torch0.4.0) rw@rw:~/新建文件夹/fssd.pytorch-master$ sh make.sh
running build_ext
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
(torch0.4.0) rw@rw:~/新建文件夹/fssd.pytorch-master$ pythondemo.py
pythondemo.py：未找到命令
(torch0.4.0) rw@rw:~/新建文件夹/fssd.pytorch-master$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    from data import AnnotationTransform, COCODetection, VOCDetection, BaseTransform, VOC_300,VOC_512,COCO_300,COCO_512, COCO_mobile_300
  File "/home/rw/新建文件夹/fssd.pytorch-master/data/__init__.py", line 3, in <module>
    from .coco import COCODetection
  File "/home/rw/新建文件夹/fssd.pytorch-master/data/coco.py", line 21, in <module>
    from utils.pycocotools.coco import COCO
  File "/home/rw/新建文件夹/fssd.pytorch-master/utils/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/rw/新建文件夹/fssd.pytorch-master/utils/pycocotools/mask.py", line 4, in <module>
    from . import _mask
ImportError: /home/rw/新建文件夹/fssd.pytorch-master/utils/pycocotools/_mask.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
`

**Comment by rw1995** [comment]
@dlyldxwl 这这样的，我运行sh make.sh 提示：
running build_ext
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)


这能理解为它什么都没做吗？

**Comment by ZCCDL** [comment]
have you solve it?

**Comment by ZCCDL** [comment]
I have solve it

**Comment by rw1995** [comment]
> 
> 
> I have solve it

how to do it?

**Comment by ZCCDL** [comment]
把utils 替换为  https://github.com/lzx1413/PytorchSSD  的，在运行make

**Comment by rw1995** [comment]
出现了一个有意思的地方，首先我安装torch0.4.0,发现不能import torch 所以我pip install torchvision 》发现自动安装了torch1.1.0 然后我根据 @ZCCDL 将utils文件夹替换，发现能运行了
现在环境 anaconda虚拟环境，python3.5+torch1.1.0+.CUDA90+CUDNN7
