### ISSUE TITLE
some wrong(how can i solve it)

### ISSUE THREAD

**Issue by rw1995** [dlyldxwl/fssd.pytorch#7]
when i  find some wrong i can't solve 
`
rw@rw:~/新建文件夹/fssd.pytorch-master$ source activate pytorch0.4.0
(pytorch0.4.0) rw@rw:~/新建文件夹/fssd.pytorch-master$ python demo.py
Finished loading model
Traceback (most recent call last):
  File "demo.py", line 114, in <module>
    test_net(net, img, img_name, detector, transform, priors,top_k=200, thresh=0.4)
  File "demo.py", line 38, in test_net
    out = net(x,test=True)
  File "/home/rw/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rw/新建文件夹/fssd.pytorch-master/models/FSSD_VGG.py", line 105, in forward
    transformed_features.append(v(source_features[k]))
  File "/home/rw/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rw/新建文件夹/fssd.pytorch-master/models/FSSD_VGG.py", line 28, in forward
    x=F.interpolate(input=x,size=(self.up_size, self.up_size), mode='bilinear')
**AttributeError: module 'torch.nn.functional' has no attribute 'interpolate'**

`
i have put weight into the folder 
but something is wrong ?
would you help me??

**Comment by rw1995** [comment]
![2019-05-18 14-22-23屏幕截图](https://user-images.githubusercontent.com/37976371/57965619-37761500-7979-11e9-8e8d-a1c6a002ac86.PNG)

**Comment by dlyldxwl** [comment]
@rw1995 
sry, I have read it until now.
Please ensure your pytorch is successfully installed, because functional has interpolate method.
Also，you can using this command to replace it.
`self.Upsample = nn.Upsample(scale_factor=self.up_size, mode='bilinear')
x = self.Upsample(x)`

**Comment by rw1995** [comment]
i will to try it,thank you
